### ISSUE TITLE
Method add_warning of Result class has different behavior than add_failure

### ISSUE THREAD

**Issue by IgnacioRV** [Skyscanner/cfripper#103]
# Description
Currently add_failure takes the values required to create a failure, creates it then adds it to the Result object's `failed_rules`
On the other hand add_warning takes a Failure object directly.

# Proposed solution
The methods should be updated so that they both have the same behavior (or maybe even just add an add_finding method which takes a `type` that can be either Failure or Warrning 😄 )

**Comment by ocrawford555** [comment]
We should now have https://github.com/Skyscanner/cfripper/blob/master/cfripper/rules/base_rules.py#L45 which replaces these methods with just one method that can handle both failures/warnings/debug mode rules :)
