### ISSUE TITLE
Validation errors for CFModel

### ISSUE THREAD

**Issue by SayantanKhanra10** [Skyscanner/cfripper#118]
I tried cfripper against an template which had below two parameters:

```
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: python3.7
    MemorySize: 256
    Timeout: 5
```

I get the below error :

```
Unhandled exception raised, please create an issue wit the error message at https://github.com/Skyscanner/cfripper/issues
Traceback (most recent call last):
  File "/private/var/folders/x3/_68l07kx74q32x0msgcs07t9md8s2c/T/tmp3as4xqx8/multiaccount/.venv/lib/python3.7/site-packages/cfripper/cli.py", line 150, in cli
    process_template(template=template, resolve_parameters=resolve_parameters, **kwargs)
  File "/private/var/folders/x3/_68l07kx74q32x0msgcs07t9md8s2c/T/tmp3as4xqx8/multiaccount/.venv/lib/python3.7/site-packages/cfripper/cli.py", line 89, in process_template
    cfmodel = get_cfmodel(template)
  File "/private/var/folders/x3/_68l07kx74q32x0msgcs07t9md8s2c/T/tmp3as4xqx8/multiaccount/.venv/lib/python3.7/site-packages/cfripper/cli.py", line 38, in get_cfmodel
    cfmodel = pycfmodel.parse(template)
  File "/private/var/folders/x3/_68l07kx74q32x0msgcs07t9md8s2c/T/tmp3as4xqx8/multiaccount/.venv/lib/python3.7/site-packages/pycfmodel/__init__.py", line 5, in parse
    return CFModel(**template)
  File "/private/var/folders/x3/_68l07kx74q32x0msgcs07t9md8s2c/T/tmp3as4xqx8/multiaccount/.venv/lib/python3.7/site-packages/pydantic/main.py", line 283, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for CFModel
Transform
  value is not a valid list (type=type_error.list)
Globals
  extra fields not permitted (type=value_error.extra)
```

**Comment by jsoucheiron** [comment]
Would you mind sharing the CF file that caused this?

**Comment by jsoucheiron** [comment]
Hi!
Is this a valid CloudFormation file, or are you feeding an AWS Serverless Application Model?

**Comment by SayantanKhanra10** [comment]
`AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
    multiaccount
    
    A template to create Python and SAM based serverless applications

Parameters:
    StackPrefix:
        Type: String
        Description: Prefix for all resources diversified by the environment (t, a, p) following the pattern 'enx{env}{stacknumber}-{stackname}'
    GlueBasePath:
        Type: String
        Description: Prefix where the scripts for Glue jobs reside
    GluePythonDependenciesPath:
        Type: String
        Description: S3 path where the library zip for Glue jobs resides
    CodeBucketName:
        Type: String
    StackEnv:
        Type: String
    StackNumber:
        Type: Number
    StackName:
        Type: String
    AppNumber:
        Type: String

Globals:
  Function:
    Runtime: python3.7
    MemorySize: 256
    Timeout: 5
    AutoPublishAlias: live
    DeploymentPreference:
      Type: Linear10PercentEvery1Minute 

Resources:
  DummyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${StackPrefix}-dummy
      Tracing: Active 
      CodeUri: functions/dummy
      Handler: lambda_function.handler
      Layers:
        - !GetAtt DependencyLayerStack.Outputs.PythonDependencyLayerArn
      Description: This function responds with a static response
        # Policies: # Example inline policy
        #     - Version: "2012-10-17"
        #     Statement:
        #         - Effect: "Allow"
        #         Action:
        #             - "ssm:GetParameter"
        #         Resource:
        #             - "*"
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
          Variables:
              PARAM1: VALUE
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /first/{proxy+}
            Method: any 
      Tags:
        environment: !Ref StackEnv
        project: !Ref StackName
        stack-name: !Ref StackName
        stack-number: !Ref StackNumber
        app-number: !Ref AppNumber

  DummyGlueJob:
    Type: "AWS::Glue::Job"
    Properties:
      Role: !Ref DummyGlueJobRole
      Name: !Sub ${StackPrefix}-dummy
      Command:
        Name: glueetl
        ScriptLocation: !Sub ${GlueBasePath}dummy/glue_job.py
      DefaultArguments:
          --extra-py-files: !Sub ${GluePythonDependenciesPath}
      MaxRetries: 0
      Description: "Transforms results data"
      AllocatedCapacity: 1
      ExecutionProperty:
        MaxConcurrentRuns: 1

  DummyGlueJobRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${StackPrefix}-glue"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - glue.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole

  DummyGluePolicy:
    Type: AWS::IAM::Policy
    Properties:
        PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Action:
                - s3:Get*
                - s3:List*
              Resource:
                - !Sub arn:aws:s3:::${CodeBucketName}
                - !Sub arn:aws:s3:::${CodeBucketName}/*
        PolicyName: !Sub ${StackPrefix}-glue-policy
        Roles:
        - !Ref DummyGlueJobRole


  DependencyLayerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./dependency_layer.yaml
      Parameters:
        StackPrefix: !Ref StackPrefix
`

**Comment by jsoucheiron** [comment]
This definitely looks like an AWS SAM stack, not a cloudformation. They are really similar, but neither pycfmodel nor cfripper support it.
We'd be happy to accept PRs that make it possible to handle this kind of stacks, but we won't be implementing this feature any time soon, as this is not something we use internally.

**Comment by SayantanKhanra10** [comment]
Ok. I will close this issue.
