### ISSUE TITLE
some X-Ray actions require * for the resource. 

### ISSUE THREAD

**Issue by caruso-billfire** [Skyscanner/cfripper#138]
https://github.com/Skyscanner/cfripper/blob/4a5858825a4cc7880bfb0b87dd370e90d0318974/cfripper/cloudformation_actions_only_accepts_wildcard.py

This file needs to have some X-Ray actions that were not included. 

some examples but not all missing actions
 
"xray:PutTraceSegments",
"xray:PutTelemetryRecords",
"xray:GetSamplingRules",
"xray:GetSamplingTargets",
"xray:GetSamplingStatisticSummaries"

**Comment by jsoucheiron** [comment]
Is this the complete list of xray actions that only allow wildcards?

**Comment by caruso-billfire** [comment]
https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsx-ray.html

can be found here, also on the left is all the services, so you can go through those as well to find all the wildcard only actions
