### ISSUE TITLE
bump click dependency to >=8

### ISSUE THREAD

**Issue by davidh-unmind** [Skyscanner/cfripper#217]

**Comment by ocrawford555** [comment]
Hey @davidh-unmind - is this impacting the ability to install CFRipper? Or is there another requirement for pinning to this version? Thanks!

**Comment by davidh-unmind** [comment]
Hi. Yes when combined with using checkov 2.0.555 deps cannot be resolved since checkov requires click >=8.0.0

**Comment by ocrawford555** [comment]
We will push this fix out as part of 1.8.0 👍🏼
