### ISSUE TITLE
ReadTheDocs link broken

### ISSUE THREAD

**Issue by dtrodrigues** [Skyscanner/cfripper#253]
As of the time of this issue creation, the link to https://cfripper.readthedocs.io/ redirects to https://cfripper.readthedocs.io/en/1.15.0/ , which doesn't currently exist.

**Comment by w0rmr1d3r** [comment]
hi @dtrodrigues ,
thank you for spotting this!
We are already looking into it. We'll keep you posted of any fix/progress on this.
Thank you 😄

**Comment by w0rmr1d3r** [comment]
hi @dtrodrigues ,
We have just released v1.15.1, fixing the documentation:
https://cfripper.readthedocs.io/en/1.15.1/

Will close this issue now. Feel free to reopen it if needed.

Thank you again for spotting it!
