### ISSUE TITLE
ReadTheDocs link broken

### ISSUE THREAD

**Issue by dtrodrigues** [Skyscanner/cfripper#276]
As of the time of this issue creation, the link to https://cfripper.readthedocs.io/ redirects to https://cfripper.readthedocs.io/en/1.15.5/ , which doesn't currently exist. This previously happened in https://github.com/Skyscanner/cfripper/issues/253

**Comment by w0rmr1d3r** [comment]
Hi @dtrodrigues , thank you for reporting this, we are looking into it

**Comment by jsoucheiron** [comment]
#275

**Comment by w0rmr1d3r** [comment]
Working again in `latest` https://cfripper.readthedocs.io/en/latest/
Will soon release `1.15.6`

**Comment by w0rmr1d3r** [comment]
hi @dtrodrigues ,
going to https://cfripper.readthedocs.io/ now redirects to https://cfripper.readthedocs.io/en/v1.15.6/
Which is the latest version available.
Thank you for reporting the issue
