### ISSUE TITLE
CLIification?

### ISSUE THREAD

**Issue by pnathan** [Skyscanner/cfripper#34]
Hi,

Wondering if there are any plans to turn this into a plain CLI tool for integrating into, e.g., CI/CD pipelines.

**Comment by jsoucheiron** [comment]
Hi, we currently do not need this feature, but we do accept PRs :)

**Comment by pnathan** [comment]
Thanks for the update. I'll see if there's anything I can do.

**Comment by jsoucheiron** [comment]
https://github.com/Skyscanner/cfripper/pull/90

**Comment by oscarbc96** [comment]
👋 @pnathan The CLI PR was merged I will close this ticket 😄
