### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by nafpliot** [Skyscanner/cfripper#66]
Hey guys, I have a problem with the lambda installation that you might be able to help me with.

I ran the `make lambda.zip` but I cannot seem to define the correct entrypoint / handler (?) in AWS. I have defined `cfripper.main.handler` but I get `Unable to import module 'cfripper.main'`.

A more detailed output of the error is `Unable to import module 'cfripper.main': No module named 'dataclasses'`, but after installing dataclasses I get `module initialization error: issubclass() arg 1 must be a class`.

Maybe I am missing something but since there is no installation documentation I don't know what I am doing wrong.

**Comment by nafpliot** [comment]
Ok. After a couple of hours I figured it out. `Dataclasses` is included by default on Python 3.7 and I was using Python 3.6 for my lambda environment... It would be cool if these type of requirements were written in the readme.

**Comment by jsoucheiron** [comment]
https://github.com/Skyscanner/cfripper/blob/master/setup.py#L29

**Comment by jsoucheiron** [comment]
I'll add a label on the readme whenever I have some time

**Comment by jsoucheiron** [comment]
Closing the issue as the README improvement was already merged
