### ISSUE TITLE
AWS S3 path format issue

### ISSUE THREAD

**Issue by midisfi** [Skyscanner/cfripper#91]
While trying to test the tool we ran into an issue with S3 bucket path failing to be recognized. The utils.py file has five tests for different ways of accessing S3 objects, but after creating a new bucket for the json object, the path was not recognized.

S3 link: https://BUCKETNAME.s3.REGION.amazonaws.com/test.json

We simply used a supported format to make this work, but it would better if the above S3 path format was recognized out of the box.

**Comment by jsoucheiron** [comment]
Could you please upload the CF file that's causing issues or a dummy file that exposes the issue?
It would help us a lot to debug the issue.

**Comment by oscarbc96** [comment]
Hi @saariomi!
Thanks for letting us know this URL format! 
Yes, we need to update this function `extract_bucket_name_and_path_from_url ` (https://github.com/Skyscanner/cfripper/blob/master/cfripper/model/utils.py#L37) to support this URL format.
Would you like to create a PR? :)

**Comment by saariomi** [comment]
Do I need some extra permissions to publish a branch and then create a PR?

**Comment by ocrawford555** [comment]
@saariomi i would recommend forking this project using the "Fork" button, making changes as necessary, including tests, and then raising a PR for review (all of which would be awesome!)

**Comment by saariomi** [comment]
Got it, please review PR.

**Comment by ocrawford555** [comment]
PR: https://github.com/Skyscanner/cfripper/pull/92

**Comment by oscarbc96** [comment]
This case is now supported on the last version of CFRipper, I will close this PR 😄
